# Generated by Django 5.2.6 on 2025-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tag_alter_plant_options_plant_user_carelog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
        migrations.AlterField(
            model_name='carelog',
            name='activity',
            field=models.CharField(choices=[('W', 'Watering'), ('F', 'Fertilizing'), ('P', 'Pruning'), ('R', 'Repotting'), ('I', 'Inspection'), ('T', 'Treatment'), ('O', 'Other')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='carelog',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
